default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  host: localhost
  database: turbolinks_development
test:
  <<: *default
  database: turbolinks_test
production:
  <<: *default
  host: <%= ENV['DATABASE_URL'] %>
  database: turbolinks_production
