# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba4124ff15d42ca92307cca6436325dfc766517727d24840393e4b0baeb77706126ead74c7b5a37679b6a97cc570c7d47d1a5cad71ee6abf83b10c9e621bd2bd

test:
  secret_key_base: 046aec1166540a2f55ce22084f61ee02475d1b919ea38388d3cb720e173851180cf152cd6189fe90d6d57e35141f186ad1e03f04d35d34f0e6e7cdc37e6525e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
